resources:
  - name: connecting_resource_node_test_1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/nodeTest
      branches:
        include: runtime      

pipelines:
  - name: node_test_run
    steps:
      - name: myStep
        type: Bash
        configuration:
          nodePool: k9s        
          outputResources:
            - name: connecting_resource_node_test_1
#               trigger: false
          integrations:
            - name: vijay
        execution:
          onExecute:
            - write_output connecting_resource_node_test_1 "test=value"

      - name: c7dynamic
        type: Bash
        configuration:     
#           nodePool: k9s
#           runtime:      
#             type: image
#             image:
#               custom:
#                 name: docker.jfrog.io/jfrog/pipelines-c7
#                 tag: 0.0.0-f11020
#                 registry: dockerDotJfrog       
          inputResources:
            - name: test_1234
            - name: connecting_resource_node_test_1
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath
#             - cd docker
            - docker buildx version
            - docker buildx build  --platform linux/amd64 -t vijaydocker1991/centos7-amd64 .
            - docker buildx build  --platform linux/arm64 -t vijaydocker1991/centos7-arm64 .
            - docker buildx build  --platform linux/arm/v7 -t vijaydocker1991/centos7-arm32 .
            - docker images

#       - name: u18dynamic
#         type: Bash
#         configuration:
#           nodePool: u18dynamic
# #           runtime:      
# #             type: image
# #             image:
# #               custom:
# #                 name: docker.jfrog.io/jfrog/pipelines-c7
# #                 tag: 0.0.0-f11020
# #                 registry: dockerDotJfrog              
#           inputResources:
#             - name: test_1234
#             - name: connecting_resource_node_test_1
#           integrations:
#             - name: vijay_docker            
#         execution:
#           onExecute:
#             - pushd $res_test_1234_resourcePath  
#             - cd docker
#             - docker buildx
#             - docker buildx build  --platform linux/amd64 -t vijaydocker1991/ubuntu18-amd64 .
#             - docker buildx build  --platform linux/arm64 -t vijaydocker1991/ubuntu18-arm64 .
#             - docker buildx build  --platform linux/arm/v7 -t vijaydocker1991/ubuntu18-arm32 .            
#             - docker images            

#       - name: u20dynamic
#         type: Bash
#         configuration:
#           runtime:      
#             type: image
#             image:
#               custom:
#                 name: docker.jfrog.io/jfrog/pipelines-c7
#                 tag: 0.0.0-f11020
#                 registry: dockerDotJfrog           
#           nodePool: u20dynamic
#           inputResources:
#             - name: test_1234
#             - name: connecting_resource_node_test_1
#           integrations:
#             - name: vijay_docker            
#         execution:
#           onExecute:
#             - pushd $res_test_1234_resourcePath
#             - cd docker
#             - docker buildx
#             - docker buildx build  --platform linux/amd64 -t vijaydocker1991/ubuntu20-amd64 .
#             - docker buildx build  --platform linux/arm64 -t vijaydocker1991/ubuntu20-arm64 .
#             - docker buildx build  --platform linux/arm/v7 -t vijaydocker1991/ubuntu20-arm32 . 
#             - docker images            

#       - name: win_2019
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#           inputResources:
#             - name: connecting_resource_node_test_1
#         execution:
#           onExecute:
#             - write-output "Hi"
#             - docker images
