resources:
  - name: connecting_resource_node_test_1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/nodeTest
      branches:
        include: runtime      

pipelines:
  - name: node_test_run
    steps:
#       - name: myStep
#         type: Bash
#         configuration:
# #           nodePool: k9s        
#           outputResources:
#             - name: connecting_resource_node_test_1
# #               trigger: false
#           integrations:
#             - name: vijay
#         execution:
#           onExecute:
#             - write_output connecting_resource_node_test_1 "test=value"

      - name: c7dynamic
        type: Bash
        configuration:     
          runtime:      
            type: image
            image:
              custom:
                name: jfpip.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f12594
                registry: vijay_docker     
          inputResources:
            - name: test_1234
#             - name: connecting_resource_node_test_1
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath
#             - cd docker
            - docker buildx version
            - docker images

      - name: u18dynamic
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: jfpip.jfrog.io/jfrog/pipelines-u18
                tag: 0.0.0-f12594
                registry: vijay_docker              
          inputResources:
            - name: test_1234
            - name: connecting_resource_node_test_1
          integrations:
            - name: vijay_docker            
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath  
            - cd docker
            - docker buildx version           
            - docker images            

      - name: u20dynamic
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: jfpip.jfrog.io/jfrog/pipelines-u20
                tag: 0.0.0-f12594
                registry: vijay_docker           
          nodePool: u20dynamic
          inputResources:
            - name: test_1234
            - name: connecting_resource_node_test_1
          integrations:
            - name: vijay_docker            
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath
            - cd docker
            - docker buildx version 
            - docker images            

#       - name: win_2019
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#           inputResources:
#             - name: connecting_resource_node_test_1
#         execution:
#           onExecute:
#             - write-output "Hi"
#             - docker images
