resources:
  - name: connecting_resource_node_test_1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: node_test_run
    steps:
#       - name: myStep112
#         type: Bash
#         configuration:
#           runtime:
#             type: host
#           outputResources:
#             - name: connecting_resource_node_test_1
# #               trigger: false
#           integrations:
#             - name: vijay
#         execution:
#           onExecute:
#             - write_output connecting_resource_node_test_1 "test=value"

      # - name: u16dynamic
      #   type: Bash
      #   configuration:
      #     nodePool: u16dynamic
      #     inputResources:
      #       - name: connecting_resource_node_test_1
      #   execution:
      #     onExecute:
      #       - printenv
      #       - docker images

      # - name: c7dynamic
      #   type: Bash
      #   configuration:
      #     runtime:
      #       type: host        
      #     nodePool: c7dynamic
      #     inputResources:
      #       - name: connecting_resource_node_test_1
      #   execution:
      #     onExecute:
      #       - printenv
      #       - docker images
      #       - node --version

      # - name: u18dynamic
      #   type: Bash
      #   configuration:
      #     runtime:
      #       type: host        
      #     nodePool: u18dynamic
      #     inputResources:
      #       - name: connecting_resource_node_test_1
      #   execution:
      #     onExecute:
      #       - printenv
      #       - docker images
      #       - node --version

      # - name: u20dynamic
      #   type: Bash
      #   configuration:
      #     runtime:
      #       type: host        
      #     nodePool: u20dynamic
      #     inputResources:
      #       - name: connecting_resource_node_test_1
      #   execution:
      #     onExecute:
      #       - printenv
      #       - docker images
      #       - node --version

      # - name: c8dynamic
      #   type: Bash
      #   configuration:
      #     nodePool: c8dynamic
      #     inputResources:
      #       - name: connecting_resource_node_test_1
      #   execution:
      #     onExecute:
      #       - printenv
      #       - docker images

      - name: win_2019
        type: PowerShell
        configuration:
          runtime:
            type: host        
          nodePool: win_2019
          inputResources:
            - name: connecting_resource_node_test_1
        execution:
          onExecute:
            - write-output "Hi"
            - docker images
            - node --version
            - (Get-Command node).Path
